### ISSUE TITLE
pdf files

### ISSUE THREAD

**Issue by tlinetrader** [Dijji/FileMeta#104]
Does this software work with pdf files? I don't see a pdf option in the association manager. Thank you.

**Comment by Dijji** [comment]
Yes, it does.

Note that the Association Manager lists extensions ordered first by what their current handler is, and only second by extension name. You will therefore have to scroll down past the extensions that already have handlers to the extensions that do not, which on a standard system, includes PDF, to see the entry that you want.

Dijji

**Comment by tlinetrader** [comment]
Thanks for your help. My apology for not carefully reading the
documentation first.

**Comment by Dijji** [comment]
No problem. I'm frequently guilty of the same 'crime' myself.
