### ISSUE TITLE
Can't View or Edit any Tags within PowerShell

### ISSUE THREAD

**Issue by alexporter7** [Dijji/FileMeta#111]
I've tried a variety of methods to both view and edit the tags added to associated files within PowerShell to automate adding tags to specific files and folders, is there any way to access these fields?

**Comment by Dijji** [comment]
A convenient way to edit tags from the command line, or within PowerShell, is to use the property editing sample that Microsoft provided in the Windows 7 era, when properties first came out. You can find it here: https://github.com/microsoft/Windows-classic-samples/tree/master/Samples/Win7Samples/winui/shell/appplatform/PropertyEdit

This will use the File Meta property handler if you have set one up for the extension.
If you don't have the ability to compile this, let me know, and I can build a version for you.

**Comment by alexporter7** [comment]
> A convenient way to edit tags from the command line, or within PowerShell, is to use the property editing sample that Microsoft provided in the Windows 7 era, when properties first came out. You can find it here: https://github.com/microsoft/Windows-classic-samples/tree/master/Samples/Win7Samples/winui/shell/appplatform/PropertyEdit
> 
> This will use the File Meta property handler if you have set one up for the extension.
> If you don't have the ability to compile this, let me know, and I can build a version for you.

I was able to find the required files and build the PropertyEdit application. It's been tested and working, thanks for pointing me in the right direction I was losing my mind trying to figure this out!

**Comment by Dijji** [comment]
Excellent, I'm glad my pointer helped. This is one of the ones that doesn't show up in searches: you just have to know where to look.
