### ISSUE TITLE
Software overwriting meta data on save. Can I store my tags in an external file somewhere?

### ISSUE THREAD

**Issue by ItsCubeTime** [Dijji/FileMeta#121]
Hi, so it seems Blender just overwrites all the meta data on save even if you make sure to modify the metadata before starting Blender.

What Ive tried is:

- PS C:\WINDOWS\system32> & "C:\Program Files\File Metadata\FileMetaAssoc.exe" -r .blend
File Meta property handler successfully removed for extension '.blend'
PS C:\WINDOWS\system32> & "C:\Program Files\File Metadata\FileMetaAssoc.exe" -r .blend
Extension '.blend' does not currently have the File Meta property handler
PS C:\WINDOWS\system32> & "C:\Program Files\File Metadata\FileMetaAssoc.exe" -a -p="office dsofile" .blend
File Meta property handler successfully added for extension '.blend'
PS C:\WINDOWS\system32> & "C:\Program Files\File Metadata\FileMetaAssoc.exe" -a -p="office dsofile" .blend
Extension '.blend' already has the File Meta property handler
PS C:\WINDOWS\system32>
* Adding a tag and author to a .blend File
* Opening the .blend w Blender
* Saving **And so the file metadata is lost here**
* Refreshing file explorer and seeing that the tag & author metadata is gone

By default Blender also uses some odd backup system where it creates a .blend1 file that represents your previous save. For the sake of avoiding some issue related to this I disabled this whilst testing.

*Any ideas for solutions are welcome*

**Comment by Dijji** [comment]
It sounds like you are running into a known limitation with File Meta. As described in the README:
" Also, if your files are still being edited, then you need to check that associated metadata is preserved on save. Some file editors, rather than update the file in place, save updates using a write-new-file, delete-original-file, rename-new-to-original strategy that loses any metadata held in the annex to the original file. "
I know of no work around, other than saving the meta data to XML before the file is edited, and reapplying it afterwards.

**Comment by ItsCubeTime** [comment]
> It sounds like you are running into a known limitation with File Meta. As described in the README:
> " Also, if your files are still being edited, then you need to check that associated metadata is preserved on save. Some file editors, rather than update the file in place, save updates using a write-new-file, delete-original-file, rename-new-to-original strategy that loses any metadata held in the annex to the original file. "
> I know of no work around, other than saving the meta data to XML before the file is edited, and reapplying it afterwards.

Alright, thanks for the reply still :) I found my way to a [software](https://tagging.connectpaste.com/) that solves this quite conveniently by storing the tags elsewhere.

**Comment by Dijji** [comment]
The software you mention is a nice piece of work, although not open source. Being focused on tags, it can provide quite a rich UI. However, I do wonder where it stores the tag information, and therefore what happens when you move a tagged file to a different folder or drive. Are the tags retained?

**Comment by ItsCubeTime** [comment]
### 

> The software you mention is a nice piece of work, although not open source. Being focused on tags, it can provide quite a rich UI. However, I do wonder where it stores the tag information, and therefore what happens when you move a tagged file to a different folder or drive. Are the tags retained?

Not sure, I cant seem to find any file neither in my %APPDATA% nor the program files intall dir.

It does come with a feature to export and import tags, however its in a binary format which might not be so nice if one wanted to migrate there tags to another tagging system/software.

![image](https://user-images.githubusercontent.com/20190653/119344129-92911f80-bc97-11eb-8a8d-abefff20cab9.png)

**Comment by ItsCubeTime** [comment]
Cant say I know of any alternatives tho that integrates with File Explorer (other than paid ones like Tabbles which is subscription based)
