### ISSUE TITLE
can I use the "Everything"?

### ISSUE THREAD

**Issue by BigbadHort** [Dijji/FileMeta#133]
"Everything"  (https://www.voidtools.com/) is very fast search utiliti
Can I use it with FileMeta?

**Comment by BigbadHort** [comment]
self-answer:
Everything working well with **docx, jpg, rar, 7z, exe, fb2, epub, bat, py**
don't working with **.cmd .md .apk** (.cmd with error)

my tested ex.:
```
"I:\777\" tag:admin
"I:\777\" rating:1
"I:\777\" author:hort
"I:\777\" category:test
```

**Comment by Maels34** [comment]
Hi how do you search tag in everything ?

**Comment by BigbadHort** [comment]
> "I:\777\" tag:admin
> "I:\777\" rating:1
> "I:\777\" author:hort
> "I:\777\" category:test
