### ISSUE TITLE
Newbie would appreciate setup help or clarification

### ISSUE THREAD

**Issue by thomasn528** [Dijji/FileMeta#34]
Hi,
This software looks like exactly what I'd like (fwiw, I want to be able to tag scanned pdfs of old family letters by family member).  But I'm not a developer or even a GitHub user (until now), and I have a feeling I'm missing some assumption about how to install it.

In particular, when I download the FileMeta-master.zip, I don't see anything I can execute as setup, neither the conventional setup.exe nor anything else within the Setup folder that I can execute.  I've also tried "cloning to GitHub desktop" after installing that software, but see no obvious way forward there either.

I'm guessing I need some other program that knows what to do with "Setup\Setup.wixproj". If so, what is it? If not, what should I do?  In either case, adding a bit more explanation to your "Getting Started" page (https://github.com/Dijji/FileMeta/wiki/Getting-Started) might be useful for those of us at the bottom of the class. :)

**Comment by thomasn528** [comment]
OK, found and successfully installed MSI files from "Releases", https://github.com/Dijji/FileMeta/releases.  I guess the other stuff is what I'd need if I aspired to tinker with the code.

**Comment by Dijji** [comment]
You have it exactly right.

Dijji
