### ISSUE TITLE
Saving a file clears its associated metadata

### ISSUE THREAD

**Issue by SuperBiagio** [Dijji/FileMeta#49]
Hi, I'm not sure if it's a bug or if I'm missing something, but working on a document which I already attached some metadata to, then modifying and saving it, makes me unable to retrieve that info again.
It's like: if a program saves the document over the preexisting file it clears the metadata associated.
Is there a sort of "versioning" in your program that controls the document "Last modified" entry to recognise to which file it has to attach its metadata? Because that would explain saving a file then losing the preexisting metadata associated to it.
I hope I made my issue comprehensible. Thanks for your work anyway, I love this!

**Comment by Dijji** [comment]
Hi

This is a problem that has been seen before, and unfortunately one I cannot do anything very satisfactory to resolve.

It comes down to how an editor that updates a file saves its changes. Remember that a file consists of a main stream, plus an alternate stream in which File Meta saves the metadata. As far as NTFS is concerned, these are a single file, and are copied, deleted, et cetera as a single unit. An editor may:
1.	Update the file in place, by writing the new content to the main stream. In this case, all is well.
2.	Update the file by writing a new temporary file containing the updated content, then, if this succeeds, deleting the original file and renaming the temporary file to the original name. In this case, the editor does not typically copy the metadata to the new file, and so the metadata is lost when the original file is deleted. This really reflects the fact that the use of alternate streams never became mainstream enough for many editors to make the investment to respect it.

The only defence that I’m aware of is to save the metadata to XML, and restore it after the edit. In some cases, it is possible to automate this as part of a save macro in the editor, using the command line versions of meta data save and restore.

I’m aware that this is unsatisfactory, but there is little else to be done, as far as I’m aware.

Dijji

**Comment by SuperBiagio** [comment]
Thank you very much for your explanatory response. Have a great day!

Il giorno gio 1 nov 2018 alle ore 09:06 Dijji <notifications@github.com> ha
scritto:
