### ISSUE TITLE
USB = tags not working

### ISSUE THREAD

**Issue by tomatoberries** [Dijji/FileMeta#58]
Hey there,

Question, I am wanting to create tags for png and pdf files and then copy those over to USB's to distribute to people. Basically, I am using the tags to create an index where people can type in "tag:_" followed by a keyword and the results pop up. I have configured my USB Drive to be NTFS which shows the tags but when I open up on a different desktop the tags are not there. I have installed the same programme on the different desktop but the tags are not restored. What is the best way to combat this so I can keep the tags on my files and copy over to multiple USB's? Thanks so much!!

**Comment by generic-github-user** [comment]
@tomatoberries did you solve this? I'm having a similar problem and would appreciate any advice you have.
