### ISSUE TITLE
Tags not carrying over

### ISSUE THREAD

**Issue by tomatoberries** [Dijji/FileMeta#59]
I've copied over files from one USB to another and noticed the tags did not carry over. Can anyone help, please?

**Comment by Dijji** [comment]
Closing an issue signals that no further action is required. Is that what you mean?

Dijji

**Comment by tomatoberries** [comment]
Yes, sorry, I had figured out what went wrong. Thank you 😊

Best Regards,


Awhina Shortcliffe
[cid:image001.jpg@01D4C9C2.897F5990]
Design Assistant

awhina@franklins.co.nz<mailto:awhina@franklins.co.nz>

Phone:  +64 (09) 303 1839

www.franklins.co.nz

[fb-01]<http://www.facebook.com/FranklinsNZ>   [linkedin-01] <http://nz.linkedin.com/company/franklin-plumbing-and-bathroomware>     [insta-01] <http://www.instagram.com/Franklins_NZ/>


  Franklins Head Office  •  24 Stadium Drive, PO BOX 310  •  Pukekohe, New Zealand 2340
