### ISSUE TITLE
Enable/Disable FileMeta as Workaround

### ISSUE THREAD

**Issue by David-Dlps** [Dijji/FileMeta#85]
AS my Windows10 Explorer.exe is crashing after installing FileMeta but the APP is awesome when I need to catalogue/find files. Is there a way to Enable/Disable FileMeta as Workaround so I can continue relaying in my Explorer.exe and only activate the FileMeta (and stand crashes) when I needed?

**Comment by Dijji** [comment]
You can simply uninstall it, and reinstall it when you need it. All the configuration will be preserved from one installation to the next.

A better workaround, though, would be for it not to crash. If it helps, I have had almost no reports of File Meta ever causing Explorer to crash: at worst, people normally get error messages saying: Failed to write property x, with obscure error codes.

What are you doing when Explorer crashes? Do you get any messages?

If the problem occurs when using the context menu, then you can choose not to install that during File Meta installation. Property handling is not optional, being rather the whole point of the thing.

As I said, your problem may be unusual, so I would appreciate it if you could try and provide more detail about what happens.

Dijji

**Comment by David-Dlps** [comment]
So far my Explorer.exe is just suddenly restarting with no error associated ... I ll check what/if are any patterns for that (it didn't happen before installing FileMeta).

**Comment by David-Dlps** [comment]
After restarting PC no crashes so far... I will be waiting/chasing the moment XD

**Comment by David-Dlps** [comment]
Just happen 1 more time after a while ... only error I could relate was this 
![image](https://user-images.githubusercontent.com/22942896/79325760-05b35880-7f12-11ea-930d-5a4835ad838e.png)

I think this issue should be closed since I cant determine the WHEN and also is not that frequent anymore.

Note. I have run the REPAIR option in the installer and all seems to be OK
