### ISSUE TITLE
Can I TAG Folders?

### ISSUE THREAD

**Issue by David-Dlps** [Dijji/FileMeta#87]
Is there a way to create a Handler for a specific Folder?
I have seen is possible via this https://www.youtube.com/watch?v=vyFhSdm4gD8
But I doubt this is stored in the same "NTFS" record as yours.

I will check in the meantime.

**Comment by David-Dlps** [comment]
well here the results:

TAGs for a Folder are saved in desktop.ini

[{F29F85E0-4FF9-1068-AB91-08002B27B3D9}] 
Prop5=31,THISISMYTAG

Here is the File that do trick
[Tag_Folder.bat.txt](https://github.com/Dijji/FileMeta/files/4466461/Tag_Folder.bat.txt)

Here a way to activate in the Menu Right Click on Win10
[activateReg_TagFolder_david.reg.txt](https://github.com/Dijji/FileMeta/files/4466460/activateReg_TagFolder_david.reg.txt)

Credits=> Taken from https://drive.google.com/file/d/1ielPA2kVfVDe4GAjprqtuO5dcX3qJyz3/view

**Comment by Dijji** [comment]
Cool. I knew about the desktop.ini capability, but this is the best packaging of it that I have seen.

It could be improved. For instance, I'm pretty sure that it's possible to extend the folder context menu to allow tags to be added and edited, which would be a more natural approach.

However, it does have important limitations. Firstly, it only deals with tag properties, whereas File Meta handles the full range of system properties. Secondly, it has copy semantics that are even slightly worse, in that the crucial information is held in a separate file within the folder. Thirdly, the properties are not searchable using the Explorer search box. 

It does turn out, however, that the same alternate stream storage used by File Meta for files is supported by NTFS for folders too. This largely answers both of the above limitations. The crucial catch, however, is that there is no way to get Explorer to display any of the property values, which makes the desktop.ini approach still the reigning champion.

But lack of support for property search has always been a deal-breaker for me in considering adding the capability to File Meta.

Dijji

**Comment by David-Dlps** [comment]
You are right ... except that these properties are searchable using Explorer search (I have tested it).

But limitations 1&2 are true and enough to not make that viable as a way for FileMeta to store props.

**Comment by Dijji** [comment]
I am encouraged to find that I am wrong, and the tags are searchable. That is very good news. Maybe the lack of extensibility to other properties does make it a bad fit for File Meta, but maybe there is room for another little project which just aims at doing a better job than the batch file-based implementation that you found. It's worth thinking about.

Thank you for pointing me to this

Dijji
