### ISSUE TITLE
Server Installation

### ISSUE THREAD

**Issue by andrewdci03** [Dijji/FileMeta#91]
For deployment/installation on servers we should be able to just take the msi, put it on the server, and run it?

Just making sure I'm clear.

Also, we will need to have this installed on the client workstations as well correct?

**Comment by andrewdci03** [comment]
Also, can we re-use your code to create different UI's

**Comment by Dijji** [comment]
The installation will certainly work on servers, though it probably is a little overweight for the purpose. You would not expect use the Association Manager there, for instance, but rather propagate the configuration from elsewhere using the command line tools.

You might want to take a look at Issue #65, which was about deployment to multiple systems, and even how to use group policy to do it, which involves stripping down the installation to what is really needed.

And yes, you can use the code to create derivative products, as long as you meet the terms described in the MS-PL licence. These relate to copyright, patents, etc.

Dijji

**Comment by andrewdci03** [comment]
Thank you for your response, I will use this thread to resolve some questions I have so I don't make too many threads.

So my company is looking for away to add metadata to any file type, and then be able to transmit that file via email, sharepoint, over a file system, etc. Now I'm new to this area so I'm still trying to understand it, but from my understanding this is solution if you're using the files locally, but once you transmit them in some form there's the possibility of still losing that metadata correct?

**Comment by Dijji** [comment]
You are right. As soon as you move the file away from an NTFS hard drive, the metadata will be lost. And this includes email, and most other forms of file transmission.

This is why File Meta provides the ability to export all the metadata to XML, and, if you like, to import it again once the file is once again resident on an NTFS hard drive to restore the original state.

You can initiate export and import either using the context menu in Explorer, or by using the provided command line utilities.

It is reasonable to wonder whether it is possible to do better this. One way is to make the metadata part of the file. But there is not always anywhere to put it. Consider the case of an empty text file. It is zero bytes long, with no scope to add anything without changing its content. But then it wouldn't be metadata.
 
What we need is a home outside the body of the file, but one that is transmitted everywhere with it. The only candidate that I've seen used is the file name. There are in fact some tagging programs out there that use this approach, so my.txt might become my[tag1 tag2].txt if the tags attached are tag1 and tag2. The problem with this is that it does not generalise well to multiple properties or cases where there is a significant amount of metadata. By the time you have included property names as well as values, and dealt with properties with complex multi-value types, you can imagine that the names will get pretty silly, and in many cases illegally long.

Up to this moment, I have not been able to think of anything better than what I do. But I'm always open to suggestions!

Dijji
